### ISSUE TITLE
Start date and time pr calendar

### ISSUE THREAD

**Issue by ehdegroot** [runely/calendar-homey#121]
i just ran into the following situation.
i have 2 calendar, private & work
i have to work tomorrow at 09:30 but i have an other event privately at 08:00.
my dynamically working alarmclock does not work anymore because the labels are filled with only the first event.
it will go off when it should be but i cannot know now at what time i have to work. the flow should do this:
time is 20:30
then: calendar is work
do: u have to work at 09:30

no matter if i have a private event.
do u have a solution for this?

**Comment by runely** [comment]
```text
my dynamically working alarmclock does not work anymore because the labels are filled with only the first event.
```

Which labels are you using? (And by labels i'm assuming you mean global tokens/tags)

- The 'Next event title' label shows events across all your calendars and will show the actual next event. So because you have an event at 08:00, which is before 09:30, it is expected behavior that the event at 08:00 is shown.

- There is labels specific for a calendar, so you should have a label called 'Todays events in work' and 'Tomorrows events in work'. These will hold respectively events today and tomorrow in the calendar work.

Hope this helps

**Comment by ehdegroot** [comment]
tokens/tags indeed :)

when i have an event in my work calendar at 09:30 but at 08:00 i have an event in my private calendar, then everything is filled with only the private event.

see screenshot:
![3DB2D903-F11A-4698-912B-A041B980F5BC](https://user-images.githubusercontent.com/37828476/91744505-e6b01d00-ebb9-11ea-8419-06d0f78d33ea.jpeg)

here u can see now that i cannot know anymore at what time i have to work. Because the private calendar has an event and  fills everything up.

any idea how to fix that?

**Comment by runely** [comment]
The labels **Todays events, title and time** and **Tomorrows events, title and time** also shows events across all your calendars! This is expected behavior.

You should have at least four other labels as well:
- **Todays events in Apple prive**
- **Tomorrows events in Apple prive**
- **Todays events in Work**
- **Tomorrows events in Work**

These labels were added in version 0.1.1.
If you don't have those labels, please check your app version.
If you installed a test version for this app at some point, the app is no longer automatically updated. Then you must install the latest release from Homey App store

**Comment by ehdegroot** [comment]
i have 0.2.4
what u see in screenshot, is what i have.

Met vriendelijke groet,

Edgar de Groot

**Comment by runely** [comment]
All this is expected behavior. However i can test how the app (performance vice) behaves when i add the following labels in there as well. This means 10 additional labels (when you have 2 calendars configured) which needs to be help up to date every minute. And all updates should be done in less than a second to not postpone the triggers to much...

- **Next event title in %calendarname%**
- **Next event start date in %calendarname%**
- **Next event start time in %calendarname%**
- **Next event stop date in %calendarname%**
- **Next event stop time in %calendarname%**

**Comment by ehdegroot** [comment]
thnx! i am curious if that solves my last issue :)

**Comment by runely** [comment]
Okei, so i have testet with these 5 extra tokens per calendar. I have for now only tested 3 iterations on both the live version and this new version to compare.

Live version uses in average 0,346 seconds to update the tokens.
The new version uses in average 0,438 seconds to update the tokens.
Thats only 0,092 seconds extra. Which is not bad.

I don't think everyone has a use case for these tokens, and 10 extra tokens is quite a lot, so i think i'm going to add a setting in the settings page where the tokens can be turned on/off.

Will this be OK?

**Comment by ehdegroot** [comment]
if that helps to keep the app steady and low in cpu/memory use, yes sure! maybe even better to keep a clean overview.

awesome!! i love it! thank you so much!!
