### ISSUE TITLE
icalCalendar has stopped working

### ISSUE THREAD

**Issue by liams239** [runely/calendar-homey#210]
Hi,

Since 2 updates icalCalendar crashes everytime.

This error is shown in Homey:

![Screenshot_20210119-072820_Homey](https://user-images.githubusercontent.com/61332057/104996608-7438c000-5a28-11eb-88a7-bf7ee39738fb.jpg)

Can you look into it?

Thanks!

**Comment by runely** [comment]
Hi, and thanks for the report. I've seen the crash reports and this is caused by the library IcalCalendar uses to parse the calendar file.

I reported this [bug](https://github.com/jens-maus/node-ical/issues/75) to the developer of the library when the first crasp report came in.

The bug in the library was fixed last night. I will push a new version of IcalCalendar with this updated library to Athom App Store later today

**Comment by runely** [comment]
New version with the updated library is now live

**Comment by liams239** [comment]
Thanks for the fast respons, and the fix ;-) !
