### ISSUE TITLE
Failed to load .ics file(s): Invalid time value

### ISSUE THREAD

**Issue by Tiwas** [runely/calendar-homey#314]
First of all, I found the other thread about this, but it didn't really help me.

How can I locate what's causing this issue? Is it possible to have the app disregard events with date/time issues?

**Comment by runely** [comment]
Hi there.

I actually had this problem myself for a couple of days, which made it possible for me to find the cause.

This is caused in a dependency that **IcalCalendar** uses, and its occuring because one or several of your events has an invalid timezone string used in the `DTSTART` property. For me the invalid timezone used was `Customized Time Zone`

Usually this problem goes away by itself after some time.

I have sent the developer of this dependency a pull request with a fix. Don't know if or when he will merge the PR into his codebase.

In the meantime i have added code to **IcalCalendar** which will catch this issue and just ignore these events. However it is not released yet

**Comment by runely** [comment]
Thats nice to hear 👍

I'll try to release it during the weekend, but no promises

**Comment by runely** [comment]
`1.0.5` was just released and should prevent this from happening again
