### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by anderhau2** [runely/calendar-homey#374]
App has been working great for a year or so, but last couple of months is has started crashing (getting a pause symbol). A restart have fixed it, and I made an automatic reboot flow for the app. But the last three weeks is has been crashing on restart. I try to restart app, and it just turn up a red line saying "stopped" and any flow with iCal in it is failing. I have rebooted Homey several times, does not change anything. ICal app stops immediately. 

App is updated to latest version. 

Please advice.

**Comment by runely** [comment]
I'm sorry I hear you're having troubles.

If you remove your calendars from the configuration screen, I assume it starts as it should

Then you can create a new flow with with "Synchronization error occurred" as a trigger and send yourself a push notification with the tokens from the trigger card. This will tell you which calendar is faulty.

Add back in the calendars in the configuration and wait for the push notification

Also please send me a diagnostics report right after it has crashed so I can have a look at what's happening

**Comment by anderhau2** [comment]
Diagnostikk: d899d03e-7019-4d2e-85bc-596a701085bf

**Comment by anderhau2** [comment]
When the app dont start at all (crash at once), I cant even get to the config page. So not possible to see or change the calendar config.

**Comment by runely** [comment]
Unfortunately the diagnostic report was empty..

However, since the app has no drivers, you can safely uninstall the app completely and install it later on and your flows will automatically be populated with the correct flow cards and tags!! I just tried this on my own Homey and all flows were updated correctly and working when the app was installed again and setup with my calendars!

So to find out what's causing this, please try the following:
1. **If possible, take a note of your calendar *url(s)* and *name(s)* so you don't have to dig around to find them later on**
2. Uninstall the app
3. Reinstall the app from App Store
4. **Before adding any config**, create a new flow with the `Synchronization error occurred` as trigger and as the action, send yourself a push notification with the tags from the trigger card.
5. Add back in 1 calendar at a time and wait 1 minute to see if this works okey.
6. Repeat step 5 until all calendars are added.

**Comment by anderhau2** [comment]
Uninstalled the app, it was gone from the Homey. Searched the app up again, hit install, it showed up in Homey with the rotating icon, and stopped. Tried to restart, same as before. Probably all the setup is still there, and something makes it crash.

**Comment by anderhau2** [comment]
Tried to make new report:
d1b8b224-34a9-447e-ae5b-5cc7adb38b62

**Comment by anderhau2** [comment]
I realized that automatic updates has been turned off on my Homey (apps are updated, but not the Homey itself). It was on version 7. Updated to latest version 8 and now you app started! Have not tried if it actually works, but as long as it starts I'm able to see/change config and so on. Will test and get back to you.

**Comment by anderhau2** [comment]
That did the trick! So, a little odd that it did not throw any error or tell me anything, but the reason was that I had not paid attention to updates comping for the Homey itself.

**Comment by runely** [comment]
Good to hear it's working again!
