### ISSUE TITLE
Bug: App crashes multiple times

### ISSUE THREAD

**Issue by tkroon89** [runely/calendar-homey#507]
**Describe the bug**
The app crashed multiple times on Homey Pro 2023

**To Reproduce**
Nothing I know of. Just wait. Last night it happened three times. I created an advanced flow checking periodically if the flow card was available. If it returned an error, it logged it and restarted it. 

**Homey:**
 - Firmware: 10.0.0 (Homey Pro 2023)
 - IcalCalendar version: v2.0.1 (but also happened on v2.0.0)

**Additional context**
Diagnostics report: 51167bdf-558d-4427-9cfe-c7e522bbde00

**Comment by runely** [comment]
The app is reaching the limit for memory and cpu usage and is therefore unloaded by Homey core. The app is not crashing.

Do you have the upgraded power supply? If not, your Homey's CPU will underclock and not perform as expected.

Can you go to https://my.homey.app , choose insights, and add `IcalCalendar - CPU` and `IcalCalendar - RAM` and then choose `The last 7 days` for the timeframe. Can you post a screenshot of these graphs?

**Comment by tkroon89** [comment]
Thank you for your quick reply. 

Yes, I have the new power adapter. I believe with the old adapter I often got a CPU clock of around 0.6 GHz.

<img width="1000" alt="Scherm­afbeelding 2023-08-06 om 11 45 09" src="https://github.com/runely/calendar-homey/assets/60198451/a456713a-42ef-4129-ab22-5b515aa67ac6">

**Comment by EsbenRasmussen** [comment]
I believe I have an identical problem... At least the description of this issue seems to match 100% to what I am experiencing.

Homey:
Firmware: 10.0.3 (Homey Pro 2023)
IcalCalendar version: v2.0.2
Additional context
Diagnostics report: 51167bdf-558d-4427-9cfe-c7e522bbde00

I haven't had any issues with Homey until I installed this app. After installing this app I also experienced a situation, where it looked like all other apps in my advanced flows were replaced by three dots. 

A restart of Homey fixed it temporarely.

I have the new adapter.

I am not able to select anything related to this app in insights - it is not listed.
![homey-no-insights-for-ical-calendar](https://github.com/runely/calendar-homey/assets/142941603/5b3e8f97-4d70-4f2d-854d-0580a8391e3f)

**Comment by runely** [comment]
Have you sent a diagnostics report, @EsbenRasmussen ? The diagnostics report id you are referring to is from the issue creator.

How many apps and devices do you guys have installed on your Homey's?

**Comment by tkroon89** [comment]
31... But only iCal crashes.

**Comment by EsbenRasmussen** [comment]
@runely Sorry about that. I edited my reply with my own diagnostic reference (6948bdf9-8957-470c-92d0-6b70326d995d).

Here is the list of apps that I have installed.
![image](https://github.com/runely/calendar-homey/assets/142941603/761f8a84-670d-4355-9b1f-418ae3228b69)

Here is what it looks like, when iCal is unresponsive and affecting the accessibility of other apps in flows.
![Homey-unstable-apps](https://github.com/runely/calendar-homey/assets/142941603/059afe7b-654b-4e83-a98a-7b03c6307f84)

**Comment by runely** [comment]
Hi @patrickener 

Please send a diagnostics report from the app page and paste the diagnostics report id here

**Comment by bbruggers** [comment]
Hi, got the same problem on the new homey pro 2023 on the old one it was working fine. But now just random crashes.

Exit Code: null, Exit Signal: SIGABRT

f3064ffd-b0a2-4e50-8666-f59fdcaca901

**Comment by runely** [comment]
IcalCalendar is using the same amount of memory on Homey Pro 2023 as it does on previous Homeys, like Homey (Early 2019). So there's no difference, memory wise, or app wise.

It might seem like Homey Pro 2023 has a lower memory limit before killing apps, even though Homey Pro 2023 has twice the size of RAM compared to previous Homey Pros...

I for one (and many others) doesn't have any problems with **IcalCalendar** using too much memory on Homey Pro 2023, or previous Homey's for that matter.

The reason why it's using this amount of memory is because the library I’m using to parse the calendars, uses two quite large npm packages:
- axios (2.1 MB in size)
- moment-timezone (7.2 MB in size)

I would suggest decreasing number of calendars to import to a maximum of three, and limit the import window to a maximum of 3 weeks.

**Comment by EsbenRasmussen** [comment]
Hi @runely
I was trying to use IcalCalendar for daily reminders for myself, my wife and our daughter.

I have now removed the calendar for our daughter and reduced number of weeks to 1 and will test the stability.

But are you saying, that you suspect that everyone who doesn't have this problem only use a maximum of two calendars?

/Esben

**Comment by runely** [comment]
I only hear from people who have problems/suggestions, and out of these two there are very few people with problems.

Those with crash problems often have more than three calendars and/or uses very large calendars and/or using a long import window.

However, this may not be the case for every crash. How much your Homey has to do besides IcalCalendar also plays in to the equation.

**Comment by runely** [comment]
I've been importing 3 calendars with an import window of 3 weeks since the release of this app and have never had a single crash on either Homey (Early 2019) or Homey Pro 2023.

**Comment by EsbenRasmussen** [comment]
That is so weird.

The app continues to crash even with just two calendars and an event time frame set to 1 week.

Now I am getting a bit desperate, because I really wish for this to work, so now I have changed event time frame to just 3 days.

What date and time format do you use?

Do you have "Next event tags per calendar" enabled?

**Comment by EsbenRasmussen** [comment]
@runely Also, you say: 

> "How much your Homey has to do besides IcalCalendar also plays in to the equation."

Would you say, that we can eliminate that, if I test by disabling all my flows and it still crashes?

**Comment by runely** [comment]
Your flows has very little to do with how much your homey has to do. It's the running apps and devices added to your homey that affects the load

**Comment by EsbenRasmussen** [comment]
@runely Ah, ok. So how do we go about debugging this thing, so we can get it to work?

**Comment by EsbenRasmussen** [comment]
Hi @runely
Just wanted to say that the latest update to 2.0.3 seems to have fixed my issue.

The app seems stable now (I have spot checked it in the last hour).

I haven't seen any crashes and I am now able to access the calendar values in my flows.

**Comment by tkroon89** [comment]
No fix for me. Also on 2.0.3, but still crashes every couple of hours.

Using 4 calendars with only 4 days of sync.

Op 14 sep. 2023 om 15:03 heeft EsbenRasmussen ***@***.***> het volgende geschreven:

﻿

Hi @runely<https://github.com/runely>
Just wanted to say that the latest update to 2.0.3 seems to have fixed my issue.

The app seems stable now (I have spot checked it in the last hour).

I haven't seen any crashes and I am now able to access the calendar values in my flows.

**Comment by runely** [comment]
Send me a new diagnostics report please. However I don't think there's much more I can do..

**Comment by tkroon89** [comment]
c658e0fa-6866-405a-99d2-1be22eccd578

Or do you prefer a report in crashed state?

Op 14 sep. 2023 om 18:38 heeft Rune Moskvil Lyngås ***@***.***> het volgende geschreven:

﻿

Send me a new diagnostics report please. However I don't think there's much more I can do..

**Comment by runely** [comment]
I've released a new version with some more improvements

**Comment by bbruggers** [comment]
i have been testing what the problem is. When i add a certain google ical calendar then the app crashes.
Even if it is the only one in the configuration,  i only sync 2 days. The other 2 google calendars work fine.

no idea why the 1 is causing the crashes

**Comment by runely** [comment]
Hmm. Interesting. Could you please add the google calendar that makes it crash and send a diagnostics report?

**Comment by patrickener** [comment]
Also my calendar continues to crash. 
I have generated a diagnostic report with diagnostics report id:  859857fe-4655-4456-85e7-066c104f06d3

**Comment by patrickener** [comment]
Tested now to create a new google calendar and that works fine but as soon as I add my original calendar the crashing starts.
As soon as I remove the old all works fine again.

**Comment by bbruggers** [comment]
> Hmm. Interesting. Could you please add the google calendar that makes it crash and send a diagnostics report?
> 
> @bbruggers

Can't re create the calendar any more. I removed it and made a new one, imported the old items.

**Comment by bbruggers** [comment]
> Tested now to create a new google calendar and that works fine but as soon as I add my original calendar the crashing starts. As soon as I remove the old all works fine again.

export the items in the crashing calendar en import them in the new one. Was the solution for me.

**Comment by runely** [comment]
Your calendar is too big @patrickener !! The calendar ics file is 12MB which leads to the app reaching its heap limit and is killed by Homey!

Clear out old and unwanted events and see how it goes. You can download the ics file by visiting the secret link to see the size of the file
