### ISSUE TITLE
Bug: Short descriptive bug title here

### ISSUE THREAD

**Issue by RenvanRoo** [runely/calendar-homey#589]
**Describe the bug**
Icalender is broken. Everything worked well, but now, it doesn't. I changed nothing.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Homey:**
 - Firmware: 10.3.5
 - IcalCalendar version: V2.7.1

**Additional context**
Whatsapp is also out off order.
![Screenshot 2024-04-23 18 23 03](https://github.com/runely/calendar-homey/assets/139113122/b6eac3d0-6475-4a69-8b26-c34faa08ad6c)

**Comment by runely** [comment]
First of all, just because something isn't working for you doesn't mean it's not working for anyone! And it surely isn't broken..

If you read the error messages you have gotten, and did a google search, you'll see that those messages means there's a network problem (on your end) or that the source you are trying to retrieve doesn't exist.

For your case, it's the later. The calendar address(es) you have entered in IcalCalendar doesn't work!

The fact that you say that **Whatsapp** is also out of order, should point you in the direction of a network issue at your end...
