### ISSUE TITLE
Bug: Crashes after short while

### ISSUE THREAD

**Issue by landsem** [runely/calendar-homey#607]
Diagnostics id: 9a931606-90dd-4d61-b0b0-570a8652a21e (Right after crash short after restart)
Diagnostics id: c08e662a-44ca-442e-a556-dbf61157e45b (Taken about 5 minutes after a restart, seems to have stabilized at this point)

Screenshot from developer tools, monitoring the app up until it crashes.
![chrome_D0X7cMBCtG](https://github.com/user-attachments/assets/6c6a34c2-79ec-4d74-b5a4-702cf4d16efa)

**Describe the bug**
I tried to trigger a sync of events through a flow card. The app crashed shortly after, and it often crashes right after restarting.

**Homey:**
 - Firmware: 12.0.2
 - IcalCalendar version: v2.9.0
 - Calendar provider: Gmail

**Additional context**
I thought maybe I had too many events in my calendar, so I tried to reduce the events to fetch to only be 2 days instead of 2 months, but the issue is still the same.
![image](https://github.com/user-attachments/assets/d8cb4403-acd7-418d-9b23-f819128dcc0c)

**Comment by runely** [comment]
I'm sorry but I can't reproduce these crashes.

On my own Homey Pro 2023 (as well as on my Homey 2019) i'm importing two Gmail agendas and one Exchange agenda and has never experienced any kind of crash.

My guess is that when these crashes happens your Homey has to much to do.

When I manually sync the calendars via the flow card, or wait for the 15th minute to let the app do the automatic sync, I see an increase in both ram and cpu on my end aswell. But never had any kind of crashes. Ever.

Occasionally these kind of issues appears and there's no way for me to reproduce this as this likely is happening because your Homey has a lot going on
