### ISSUE TITLE
Bug: On Event Change, numeric variable for duration not available

### ISSUE THREAD

**Issue by johnkellen** [runely/calendar-homey#613]
In homey advanced flows; 

Event added to calendar -> in list of available variables, there is a numeric variable "duration in minutes".

In Event changed -> duration in minutes is not available? 

Result: when an event is added, and the variables are added to the logic text & numeric variables of homey, the duration of a CHANGED event is not updated and so the numeric variable in homey logic can be faulty...

**Homey:**
 - Firmware: latest
 - IcalCalendar version: latest
 - Calendar provider (Gmail, Office365, Apple, ...): Gmail

**Additional context**

**Comment by runely** [comment]
This is not a bug, but by design.

`Duration in minutes` hasn't been added to **Event changed** trigger because there hasn't been any real use cases for it.

I don't understand what you need it for. Could you elaborate? Perhaps even add a screenshot of your advanced flow

**Comment by johnkellen** [comment]
Hi there

Thank you for responding.

As I use the duration in minutes from calendar events, I am now forced to
delete the event and recreate it because the duration is not updated when
changing an event.
It also seems logical to me that all variables retrieved from a created
event get updated when changing an event.

Would ik be hard to add it?

Thank you in advance

Kind regards

John

**Comment by runely** [comment]
To clarify: The `Duration in minutes` is **NOT** a property on the calendar events stored / retrieved in _IcaCalendar_. The `Duration in minutes` is a token (variable) conveniently available on most of the triggers.

What do you mean by this? 🤔 The `Duration in minutes` is **NOT** a property on the calendar events stored / retrieved in _IcaCalendar_. So this makes no sense to me

> I am now forced to
delete the event and recreate it because the duration is not updated when
changing an event

It's absolutely no problem to add it to the `Event changed` trigger.

**Comment by runely** [comment]
`Duration` and `Duration in minutes` have been added to the trigger `Event changed` in **IcalCalendar v2.10.0**.

I will be available in the app store after athom review
