### ISSUE TITLE
Bug: iCal Calender reageert niet in Homey Pro

### ISSUE THREAD

**Issue by CEC799** [runely/calendar-homey#626]
589f0e1b-4c5d-46b8-9777-560b49477268

**Comment by runely** [comment]
First of all, always send diagnostic reports in English! Don't assume the entire world knows the language you are using...

Second, when opening a issue ticket, always fill out as much information as you can! Just adding the diagnostics report is not helpful 👎

The diagnostics report you sent shows me what the problem is. If it hadn’t, i would have no idea what you were asking help about!

**Comment by runely** [comment]
The reason **IcalCalendar** isn't doing anything is because your calendar has 0 events.

Copy the ics url you have configured in the settings and open it in a web browser which will download the .ics file, open it and see that there's 0 events. It's just the `BEGIN:VCALENDAR` and `END:VCALENDAR`

**Comment by CEC799** [comment]
THANKS!


Chris Couwet
