### ISSUE TITLE
Events starts in... trigger

### ISSUE THREAD

**Issue by MatsAnd** [runely/calendar-homey#7]
Would be nice to have a trigger that triggers when an event starts in x minutes..

Example: When event starts in 5 minutes - pause Sonos speaker.

**Comment by DennisTornkvist** [comment]
First GREAT app have been waiting for this one since 2017. I would like to know the activitys during the day. Its very similar to Event starts in ... but more like event starts during the day.

Example: WHEN, event start during the day THEN text to speech: Your activities today are : (meetingtitles) 

If its hard tot implement maybe do this another way ?

**Comment by runely** [comment]
Would a global token be sufficient? Containing your activities from now on out through the day. Then you could use that global token with any app and service on the Homey, including Homey's builtin text-to-speech or Google TTS.

**Comment by MatsAnd** [comment]
How about a couple of global tokens like these?

- Next event title
- Next event starts
- Next event starts in (minutes)?
- Next event stops?
- Next event duration? (hours/minutes? TTS friendly?)
- Todays events (brief titles and start/end dates, in Google TTS friendly format)?
- Todays event count

**Comment by DennisTornkvist** [comment]
Fantastic Idea where do I donate to this fantastic endevour?

**Comment by runely** [comment]
@DennisTornkvist : Global flow tokens are coming in the next version (0.0.6) 👍

**Comment by DennisTornkvist** [comment]
Fantastic news looking forward to it.
